<?php if ($this->pageCount): ?>
<div class="row-fluid module-row ">
    <div class="span12">
        <div class="row-fluid">
            <div class="pagination pull-right">
                <ul>
                      <!-- Page Size links -->
                       <?php $pageSize = (int)$pageSize; 
                              $selectedClassName = 'pagesize-selected zf-green'; ?>
                      <li>
                        <a href="<?php $selected = ($pageSize === 15) ? $selectedClassName : '';  
                        echo $this->url('home/query',  array( 'page'=>1, 'page_size' =>15, 'query' => $query)); ?>" class="paginationcount <?=$selected ?>">15</a>
                    </li>
                   <li>
                        <a href="<?php $selected = ($pageSize === 50) ? $selectedClassName : '';
                        echo $this->url('home/query', array( 'page'=>1, 'page_size' =>50, 'query' => $query)); ?>" class="paginationcount <?=$selected ?>">50</a>
                    </li>
                     <li>
                        <a href="<?php $selected = ($pageSize === 100) ? $selectedClassName : '';
                        echo $this->url('home/query', array( 'page'=>1, 'page_size' =>100, 'query' => $query)); ?>" class="paginationcount  <?=$selected ?>">100</a>
                    </li>
                                  

                    <?php if(isset($this->previous)): ?>
                    <!-- First page link -->
                    <li>
                        <a href="<?php echo $this->url('home/query', array('page' => $this->first, 'query' => $query)); ?>">&lt;&lt; First</a>
                    </li>

                    <!-- Previous page link -->
                    <li>
                        <a href="<?php echo $this->url('home/query', array('page' => $this->previous,'query' => $query)); ?>">Previous &gt;</a>
                    </li>
                    <?php endif; ?>


                    <!-- Numbered page links -->
                    <?php foreach ($this->pagesInRange as $page): ?>
                    <li<?php echo ($page == $this->current) ? ' class="active"' : ''; ?>>
                        <a href="<?php echo $this->url('home/query', array('page' => $page, 'query' => $query)); ?>"><?php echo $page; ?></a>
                    </li>
                    <?php endforeach; ?>

                    <?php if(isset($this->next)): ?>
                    <!-- Next page link -->
                    <li>
                        <a href="<?php echo $this->url('home/query', array('page' => $this->next,'query' => $query)); ?>">Next &gt;</a>
                    </li>

                    <!-- Last page link -->
                    <li>
                        <a href="<?php echo $this->url('home/query', array('page' => $this->last, 'query' => $query)); ?>">Last &gt;&gt;</a>
                    </li>
                    <?php endif; ?>
                </ul>
            </div>
        </div>
    </div>
</div>
<?php endif; ?>